POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpZ29sZSIsImlkIjoiNjY5ZmIzNzYxMzAyNjc2OWEzNDhlMmFhIiwiaWF0IjoxNzIxODE2NTg1fQ.BqHqF0U_Rx8zxVBD7q3UGa1WFgXnzXA4w0_ryAjuMYE

{
    "title": "Other Blog By Tigole",
    "author": "Tigole",
    "url": "tigole.com/other",
    "likes": 123,
    "userId": "669fb37613026769a348e2aa"
}